#!/usr/bin/env sh

# 현재 브렌치의 네임을 branch에 저장
branch="$(git rev-parse --abbrev-ref HEAD)"

ROOT="$(git rev-parse --show-toplevel)"

# CI 환경에서 훅 스킵
if [ "$CI" = "true" ]; then
  echo "🔄 [Husky] pre-push skipped in CI environment"
  exit 0
fi

# branch가 main 이라면 문구를 노출 시키며 종료
if [ "$branch" = "main" ]; then
  echo "You can't commit directly to main branch"
  exit 1
fi

if [ "$branch" = "dev" ]; then
  echo "You can't commit directly to dev branch"
  exit 1
fi

if [ "$branch" = "staging" ]; then
  echo "You can't commit directly to staging branch"
  exit 1
fi

if [ "$branch" != "main" ] && [ "$branch" != "dev" ] && [ "$branch" != "staging" ]; then
  echo "👀  Start Inspection"
  #chmod +x $ROOT/ts-staged.sh || exit 1
  #bash "$ROOT/ts-staged.sh" || exit 1
  echo "👏  End Inspection"
fi
