#!/usr/bin/env sh
# 현재 브렌치의 네임을 branch에 저장
branch="$(git rev-parse --abbrev-ref HEAD)"

# branch가 main 이라면 문구를 노출 시키며 종료
if [ "$branch" = "main" ]; then
  echo "You can't push directly to main branch"
  exit 1
fi

# branch가 dev 이라면 문구를 노출 시키며 종료
if [ "$branch" = "dev" ]; then
  echo "You can't push directly to dev branch"
  exit 1
fi

if [ "$branch" = "staging" ]; then
  echo "You can't push directly to staging branch"
  exit 1
fi
echo "$($branch)"
echo "$($branch)"
echo "$($branch)"
echo "$($branch)"
echo "$($branch)"
echo "$($branch)"
echo "$($branch)"
echo "$($branch)"


# husky 스크립트를 쉽게 제공해주는  _/husky.sh 스크립트를 실행합니다.
. "$(dirname -- "$0")/_/husky.sh"
