name: Selective Build

on:
  pull_request:
    branches:
      - main
      - dev
      - staging

env:
  NEXT_TELEMETRY_DISABLED: '1'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set NX SHAs
        run: |
          echo "NX_BASE=${{ github.event.pull_request.base.sha }}" >> $GITHUB_ENV
          echo "NX_HEAD=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV

      - uses: actions/setup-node@v5
        with:
          node-version: 22.17.1
          cache: 'yarn'

      - name: Cache Nx
        uses: actions/cache@v5
        with:
          path: .nx/cache
          key: nx-${{ runner.os }}-${{ hashFiles('yarn.lock') }}-${{ github.sha }}
          restore-keys: |
            nx-${{ runner.os }}-${{ hashFiles('yarn.lock') }}-
            nx-${{ runner.os }}-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Reset Nx
        run: yarn nx reset

      - name: Build affected
        run: yarn nx affected -t build --verbose